import Servicio from "../src/models/Servicio";

const servicios: Servicio[] = [
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Pelvis completa",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Tira",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Cavado",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Cavado profundo",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Media Pierna",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Pierna entera",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Pecho",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Brazos",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Depilacion",
    nombre: "Glúteo",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Reiki",
    nombre: "Clase",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Reiki",
    nombre: "Curso",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Otros",
    nombre: "Peeling corporal",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
  {
    id: 1,
    categoria: "Otros",
    nombre: "Limpieza de cutis",
    precio: "200",
    descanso: "15",
    tiempo: "20",
  },
];

export default servicios;
